### ISSUE TITLE
mochiweb_request case_clause problem

### ISSUE THREAD

**Issue by congleetea** [emqtt/mochiweb#3]
Hi, I got this info in the log:
`11:46:09.680 <0.994.0> [info] Client(7610311000ex075H2FvTNIK@192.168.33.10:37152):Shutdown for {{case_clause,{error,einval}},[{mochiweb_request,get,2,[{file,"src/mochiweb_request.erl"},{line,96}]},{emqttd_ws_client,handle_info,2,[{file,"src/emqttd_ws_client.erl"},{line,220}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}`

here , the function got a result {error, einval}, however in the src/mochiweb_request.erl in line 96 [https://github.com/emqtt/mochiweb/blob/master/src/mochiweb_request.erl#L96-L114](url) , there is just a {error, enotconn}, so it can not math it. 
should it be fixed?
thanks.

**Comment by emqplus** [comment]
Fixe in commit: https://github.com/emqtt/mochiweb/commit/5c7d6fdf23b7271dde1feef878e223330d0055a5
